// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUrl = process.env["DATABASE_URL"]!;
const authToken = process.env["DATABASE_AUTH_TOKEN"];
const fullUrl = authToken ? `${dbUrl}?authToken=${authToken}` : dbUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: fullUrl,
  },
});
